### ISSUE TITLE
Set a texture saying the price of the weapons

### ISSUE THREAD

**Issue by TheBreadGuy** [Sheol-Valley/Sheol-Valley#10]

**Comment by whoknowsmeasiam** [comment]
Is it fixed?  I don't see where I have a task?

**Comment by whoknowsmeasiam** [comment]
![Gunadmin_008](https://github.com/Sheol-Valley/Sheol-Valley/assets/155835714/c6c5dbb4-84d2-4db1-9ce4-8a6fc0757a7e)

**Comment by whoknowsmeasiam** [comment]
That works

**Comment by whoknowsmeasiam** [comment]
Go it.  I've figured out.  I don't see where I can state I've completed the task.  Or do you do that after I send the work?

**Comment by whoknowsmeasiam** [comment]
![SV weapon prices](https://github.com/Sheol-Valley/Sheol-Valley/assets/155835714/6fe68382-5080-4513-b652-a398ca4277d3)

**Comment by whoknowsmeasiam** [comment]
Sorry thought you wanted boobies
