### ISSUE TITLE
Weapons don't draw correctly

### ISSUE THREAD

**Issue by whoknowsmeasiam** [Sheol-Valley/Sheol-Valley#30]
type /7 draw handgun it pulls out knife
similar probelms with other weapons.  Weapon pulls correctly at second attempt

**Comment by MattySL** [comment]
check have right gestures loadddded

**Comment by MattySL** [comment]
if you have other gestures using the same keys. If you have the old gestures enabled, firestorm pick random one of the gestures, that means, firestorm can use the old gesture and not the new. This happen not only with guns but with reload "R" for example.
